### ISSUE TITLE
The initial cutscene has a bit of whacky camera 

### ISSUE THREAD

**Issue by Miepee** [TheyCallMeXander/AM2R-SA-X-Duels#1]

**Comment by TheyCallMeXander** [comment]
Elaboration: When entering a Match as the SA-X the camera starts lower and then makes it's way up to the SA-X' start position on the statue. This is a result of multiple "oCameraLimit" objects giving information to the Camera, which cannot immediately snap to samus due to the Morph Tunnel CameraLimit giving it "smooth panning" rules.

**Comment by TheyCallMeXander** [comment]
Unsure how to tackle this issue, leaving it for now.

**Comment by TheyCallMeXander** [comment]
Fixed!
